#!/bin/bash -ue
cat remove_dups.log > merge_assignment.log
    cat split.REF_HUMAN_Y.bam.bed split.REF_HUMAN_21.bam.bed split.REF_HUMAN_MT.bam.bed split.REF_HUMAN_22.bam.bed split.REF_HUMAN_18.bam.bed split.REF_HUMAN_20.bam.bed split.REF_HUMAN_14.bam.bed split.REF_HUMAN_19.bam.bed split.REF_HUMAN_15.bam.bed split.REF_HUMAN_16.bam.bed split.REF_HUMAN_13.bam.bed split.REF_HUMAN_17.bam.bed split.REF_HUMAN_10.bam.bed split.REF_HUMAN_12.bam.bed split.REF_HUMAN_11.bam.bed split.REF_HUMAN_9.bam.bed split.REF_HUMAN_X.bam.bed split.REF_HUMAN_4.bam.bed split.REF_MOUSE_14.bam.bed split.REF_MOUSE_13.bam.bed split.REF_MOUSE_10.bam.bed split.REF_MOUSE_18.bam.bed split.REF_HUMAN_6.bam.bed split.REF_nonstand.bam.bed split.REF_MOUSE_Y.bam.bed split.REF_HUMAN_3.bam.bed split.REF_HUMAN_7.bam.bed split.REF_MOUSE_15.bam.bed split.REF_HUMAN_2.bam.bed split.REF_MOUSE_17.bam.bed split.REF_MOUSE_4.bam.bed split.REF_MOUSE_1.bam.bed split.REF_MOUSE_X.bam.bed split.REF_MOUSE_8.bam.bed split.REF_HUMAN_1.bam.bed split.REF_MOUSE_7.bam.bed split.REF_HUMAN_8.bam.bed split.REF_MOUSE_12.bam.bed split.REF_MOUSE_16.bam.bed split.REF_MOUSE_19.bam.bed split.REF_MOUSE_6.bam.bed split.REF_MOUSE_9.bam.bed split.REF_MOUSE_MT.bam.bed split.REF_MOUSE_2.bam.bed split.REF_MOUSE_5.bam.bed split.REF_HUMAN_5.bam.bed split.REF_MOUSE_3.bam.bed split.REF_MOUSE_11.bam.bed > "HEK.bed"
    sort -m -k1,1 -k2,2 split.REF_HUMAN_Y.bam_ga.txt split.REF_HUMAN_21.bam_ga.txt split.REF_HUMAN_MT.bam_ga.txt split.REF_HUMAN_22.bam_ga.txt split.REF_HUMAN_18.bam_ga.txt split.REF_HUMAN_20.bam_ga.txt split.REF_HUMAN_14.bam_ga.txt split.REF_HUMAN_19.bam_ga.txt split.REF_HUMAN_15.bam_ga.txt split.REF_HUMAN_16.bam_ga.txt split.REF_HUMAN_13.bam_ga.txt split.REF_HUMAN_17.bam_ga.txt split.REF_HUMAN_10.bam_ga.txt split.REF_HUMAN_12.bam_ga.txt split.REF_HUMAN_11.bam_ga.txt split.REF_HUMAN_9.bam_ga.txt split.REF_HUMAN_X.bam_ga.txt split.REF_HUMAN_4.bam_ga.txt split.REF_MOUSE_14.bam_ga.txt split.REF_MOUSE_13.bam_ga.txt split.REF_MOUSE_10.bam_ga.txt split.REF_MOUSE_18.bam_ga.txt split.REF_HUMAN_6.bam_ga.txt split.REF_nonstand.bam_ga.txt split.REF_MOUSE_Y.bam_ga.txt split.REF_HUMAN_3.bam_ga.txt split.REF_HUMAN_7.bam_ga.txt split.REF_MOUSE_15.bam_ga.txt split.REF_HUMAN_2.bam_ga.txt split.REF_MOUSE_17.bam_ga.txt split.REF_MOUSE_4.bam_ga.txt split.REF_MOUSE_1.bam_ga.txt split.REF_MOUSE_X.bam_ga.txt split.REF_MOUSE_8.bam_ga.txt split.REF_HUMAN_1.bam_ga.txt split.REF_MOUSE_7.bam_ga.txt split.REF_HUMAN_8.bam_ga.txt split.REF_MOUSE_12.bam_ga.txt split.REF_MOUSE_16.bam_ga.txt split.REF_MOUSE_19.bam_ga.txt split.REF_MOUSE_6.bam_ga.txt split.REF_MOUSE_9.bam_ga.txt split.REF_MOUSE_MT.bam_ga.txt split.REF_MOUSE_2.bam_ga.txt split.REF_MOUSE_5.bam_ga.txt split.REF_HUMAN_5.bam_ga.txt split.REF_MOUSE_3.bam_ga.txt split.REF_MOUSE_11.bam_ga.txt > "HEK_ga.txt"

    datamash -g 1,2 count 2 < "HEK_ga.txt"     | gzip > "HEK.gz"


    umi=`cat split.REF_HUMAN_Y.bam_umi_count.txt split.REF_HUMAN_21.bam_umi_count.txt split.REF_HUMAN_MT.bam_umi_count.txt split.REF_HUMAN_22.bam_umi_count.txt split.REF_HUMAN_18.bam_umi_count.txt split.REF_HUMAN_20.bam_umi_count.txt split.REF_HUMAN_14.bam_umi_count.txt split.REF_HUMAN_19.bam_umi_count.txt split.REF_HUMAN_15.bam_umi_count.txt split.REF_HUMAN_16.bam_umi_count.txt split.REF_HUMAN_13.bam_umi_count.txt split.REF_HUMAN_17.bam_umi_count.txt split.REF_HUMAN_10.bam_umi_count.txt split.REF_HUMAN_12.bam_umi_count.txt split.REF_HUMAN_11.bam_umi_count.txt split.REF_HUMAN_9.bam_umi_count.txt split.REF_HUMAN_X.bam_umi_count.txt split.REF_HUMAN_4.bam_umi_count.txt split.REF_MOUSE_14.bam_umi_count.txt split.REF_MOUSE_13.bam_umi_count.txt split.REF_MOUSE_10.bam_umi_count.txt split.REF_MOUSE_18.bam_umi_count.txt split.REF_HUMAN_6.bam_umi_count.txt split.REF_nonstand.bam_umi_count.txt split.REF_MOUSE_Y.bam_umi_count.txt split.REF_HUMAN_3.bam_umi_count.txt split.REF_HUMAN_7.bam_umi_count.txt split.REF_MOUSE_15.bam_umi_count.txt split.REF_HUMAN_2.bam_umi_count.txt split.REF_MOUSE_17.bam_umi_count.txt split.REF_MOUSE_4.bam_umi_count.txt split.REF_MOUSE_1.bam_umi_count.txt split.REF_MOUSE_X.bam_umi_count.txt split.REF_MOUSE_8.bam_umi_count.txt split.REF_HUMAN_1.bam_umi_count.txt split.REF_MOUSE_7.bam_umi_count.txt split.REF_HUMAN_8.bam_umi_count.txt split.REF_MOUSE_12.bam_umi_count.txt split.REF_MOUSE_16.bam_umi_count.txt split.REF_MOUSE_19.bam_umi_count.txt split.REF_MOUSE_6.bam_umi_count.txt split.REF_MOUSE_9.bam_umi_count.txt split.REF_MOUSE_MT.bam_umi_count.txt split.REF_MOUSE_2.bam_umi_count.txt split.REF_MOUSE_5.bam_umi_count.txt split.REF_HUMAN_5.bam_umi_count.txt split.REF_MOUSE_3.bam_umi_count.txt split.REF_MOUSE_11.bam_umi_count.txt | awk '{ sum += $1 } END { print sum }'`
    read=`cut -f2 HEK.read_count.txt`
    perc=$(echo "100.0 * (1 - $umi/$read)" | bc -l)
    printf "%-18s   %10d    %10d    %7.1f\n" HEK $read $umi $perc     >"HEK.duplication_rate_stats.txt"

    printf "
        remove_dups ending reads  : $(wc -l HEK.bed | awk '{print $1;}')


        Read assignments:
$(awk '{count[$3]++} END {for (word in count) { printf "            %-20s %10i\n", word, count[word]}}' HEK_ga.txt)

" >> merge_assignment.log

    printf "** End processes 'remove duplicates, assign_genes, merge_assignment' at: $(date)

" >> merge_assignment.log
